- name: Hello World
  #hosts: web  name of the other server private IP configured in the inventory.ini
  hosts: local
  connection: local
  tasks:
  - name: print hello World
    ansible.builtin.debug:
      msg: "Hello World! from ansible debug module"

- name: PLAY-2
  #hosts: web  name of the other server private IP configured in the inventory.ini
  hosts: local
  connection: local
  tasks:
  - name: play-2 and task-1
    ansible.builtin.debug:
      msg: "Hello from PLAY-2 and TASK-1"