- name: Hello World
  hosts: remote
  #hosts: local
  #connection: local
  tasks:
  - name: print hello World
    ansible.builtin.debug:
      msg: "Hello World! from ansible debug module"

- name: PLAY-2
  hosts: remote
  #hosts: local
  #connection: local
  tasks:
  - name: play-2 and task-1
    ansible.builtin.debug:
      msg: "Hello from PLAY-2 and TASK-1"